site_name: Lab1 Arnautova K33422
site_url: https://report.com/
theme:
  name: readthedocs
nav:
  - Title: index.md
  - Task 1: task1.md
  - Task 2: task2.md
  - Task 3: task3.md
  - Task 4: task4.md
  - Task 5: task5.md

theme:
  name: readthedocs