site_name: Отчет по лабораторным работам
theme:
  name: readthedocs
nav:
  - Лабораторная №1:
      - Title: lab1/index.md
      - Task 1: lab1/task1.md
      - Task 2: lab1/task2.md
      - Task 3: lab1/task3.md
      - Task 4: lab1/task4.md
      - Task 5: lab1/task5.md
  - Лабораторная №2:
      - models: lab2/models.md
      - forms: lab2/forms.md
      - views: lab2/views.md
      - urls: lab2/urls.md
      - Выводы: lab2/itog.md